log-level: debug
proxy: ""
cron: "*/10 * * * *"
initialRunupPeriod: 172800 # 48h in seconds
database:
  path: "../data/database.db" 
btcmap:
  # ZULU is substituted in code
  url-fmt: "https://api.btcmap.org/v4/places\
    ?fields=osm:addr:city,osm:name,lat,lon,osm_id,created_at,updated_at,deleted_at\
    &updated_since=[ZULU]&include_deleted=true"
geoapify:
  url-fmt: "https://api.geoapify.com/v1/geocode/reverse?lat=[LAT]&lon=[LON]&apiKey=[GEOAPIFY_API_KEY]"
nominatim:
  url-fmt: "https://btcmap-nominatim-proxy:3000/geo?lat=[LAT]&lon=[LON]"
zmq:
  url: "tcp://0.0.0.0:3000"