FROM node:18-alpine AS base

# Reusable function for installing a module
# ============================================
FROM base AS custom-error
WORKDIR /usr/custom-error
COPY ./custom-error/package.json ./
COPY ./custom-error/index.js ./
RUN npm install --production

FROM base AS http-utils
WORKDIR /usr/http-utils
COPY ./http-utils/package.json ./
COPY ./http-utils/index.js ./
RUN npm install --production

FROM base AS btcmap-common
WORKDIR /usr/btcmap-common
COPY ./btcmap-common/package.json ./
COPY ./btcmap-common/src ./src
COPY ./btcmap-common/index.js ./
RUN npm install --production

FROM base AS btcmap-database
WORKDIR /usr/btcmap-database
COPY ./btcmap-database/package.json ./
COPY ./btcmap-database/src ./src
COPY ./btcmap-database/index.js ./
RUN npm install --production

FROM base AS nominatim
WORKDIR /usr/nominatim
COPY ./nominatim/package.json ./
COPY ./nominatim/src ./src
COPY ./nominatim/index.js ./
RUN npm install --production

FROM base AS translation
WORKDIR /usr/translation
COPY ./translation/package.json ./
COPY ./translation/src ./src
COPY ./translation/index.js ./
RUN npm install --production

FROM base AS btcmap-jsonata
WORKDIR /usr/btcmap-jsonata
COPY ./btcmap-jsonata/package.json ./
COPY ./btcmap-jsonata/src ./src
COPY ./btcmap-jsonata/index.js ./
RUN npm install --production

# Final stage: Pull everything together (using the same base image)
# ============================================
FROM base AS builder

WORKDIR /usr
COPY --from=custom-error /usr/custom-error ./custom-error
COPY --from=http-utils /usr/http-utils ./http-utils
COPY --from=btcmap-common /usr/btcmap-common ./btcmap-common
COPY --from=btcmap-database /usr/btcmap-database ./btcmap-database
COPY --from=nominatim /usr/nominatim ./nominatim
COPY --from=translation /usr/translation ./translation
COPY --from=btcmap-jsonata /usr/btcmap-jsonata ./btcmap-jsonata

WORKDIR /usr/btcmap-telegram
COPY ./btcmap-telegram/package.json ./
RUN npm install --production

FROM builder
WORKDIR /usr/btcmap-telegram
COPY ./btcmap-telegram/src ./src

CMD ["npm", "start"]
